model = "gpt-5.5"
model_reasoning_effort = "high"
personality = "friendly"

approval_policy = "never"
sandbox_mode = "danger-full-access"
web_search = "live"

notify = ["/Users/akash/.codex/computer-use/Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient", "turn-ended"]

[mcp_servers.next-devtools]
command = "bunx"
args = ["-y", "next-devtools-mcp@latest"]
enabled = false

[mcp_servers.linear]
url = "https://mcp.linear.app/mcp"

[mcp_servers.paper]
url = "http://127.0.0.1:29979/mcp"
enabled = false

[mcp_servers.figma]
url = "https://mcp.figma.com/mcp"
enabled = false

[mcp_servers.laravel-boost]
command = "php"
args = ["artisan", "boost:mcp"]
enabled = false

[mcp_servers.chrome_devtools]
args = ["chrome-devtools-mcp@latest", "--auto-connect=true"]
command = "bunx"
enabled = false


[projects."/Users/akash/Developer/dotfiles"]
trust_level = "trusted"

[projects."/Users/akash/Developer/pcplatform"]
trust_level = "trusted"

[projects."/Users/akash"]
trust_level = "trusted"

[projects."/Users/akash/Developer/fg-tasks"]
trust_level = "trusted"

[projects."/Users/akash/Developer/potionpapers"]
trust_level = "trusted"

[projects."/Users/akash/Developer/semann-slattery-com"]
trust_level = "trusted"

[projects."/Users/akash/Developer/invoices"]
trust_level = "trusted"

[projects."/Users/akash/Developer/web-tools"]
trust_level = "trusted"

[projects."/Users/akash/Developer/akashpomal.com"]
trust_level = "trusted"

[projects."/Users/akash/Developer/rgconnect"]
trust_level = "trusted"

[projects."/Users/akash/Developer/semannslattery.com"]
trust_level = "trusted"

[projects."/Users/akash/Developer/momentum"]
trust_level = "trusted"

[projects."/Users/akash/Developer/neovim"]
trust_level = "trusted"

[projects."/Users/akash/Developer/replicache-rpc"]
trust_level = "trusted"

[projects."/Users/akash/Developer/fluent-ai"]
trust_level = "trusted"

[projects."/Users/akash/Developer/cms-semannslattery-com"]
trust_level = "trusted"

[projects."/Users/akash/Developer/www-semannslattery-com"]
trust_level = "trusted"

[projects."/Users/akash/Developer/wp-nanoplatform-com"]
trust_level = "trusted"

[projects."/Users/akash/Documents/Codex/2026-05-03/can-you-help-me-build-a"]
trust_level = "trusted"

[projects."/"]
trust_level = "trusted"

[projects."/Users/akash/Developer/web-tools-wordpress-plugin"]
trust_level = "trusted"

[projects."/Users/akash/Documents/Codex/2026-05-06/can-you-help-me-understand-why"]
trust_level = "trusted"

[projects."/Users/akash/Developer/www-omikastechsolve-com"]
trust_level = "trusted"

[projects."/Users/akash/Documents/Codex/2026-05-11/can-you-help-me-compress-this"]
trust_level = "trusted"

[projects."/Users/akash/Documents/Codex/2026-05-12/i-have-these-two-images-can"]
trust_level = "trusted"

[projects."/Users/akash/Documents/Codex/2026-05-13/here-s-what-my-boss-was"]
trust_level = "trusted"

[projects."/Users/akash/Developer/happy-boy"]
trust_level = "trusted"

[projects."/Users/akash/Documents/Codex/2026-05-15/what-do-you-think-of-this"]
trust_level = "trusted"

[projects."/Users/akash/Documents/Codex/2026-05-16/can-you-please-help-me-find"]
trust_level = "trusted"

[projects."/Users/akash/Documents/Codex/2026-05-16/what-d-you-make-of-these"]
trust_level = "trusted"

[projects."/Users/akash/Developer/opencode"]
trust_level = "trusted"

[projects."/Users/akash/Documents/Codex/2026-05-17/can-you-help-me-understand-what"]
trust_level = "trusted"

[projects."/Users/akash/Documents/Codex/2026-05-17/what-d-you-make-of-this"]
trust_level = "trusted"

[projects."/Users/akash/Documents/Codex/2026-05-17/can-you-help-me-outline-all"]
trust_level = "trusted"

[notice]
"hide_gpt-5.1-codex-max_migration_prompt" = true

[notice.model_migrations]
"gpt-5.1-codex-max" = "gpt-5.2-codex"

[features]
multi_agent = true
memories = true
chronicle = true

[plugins."google-calendar@openai-curated"]
enabled = true

[plugins."gmail@openai-curated"]
enabled = true

[plugins."github@openai-curated"]
enabled = true

[plugins."google-drive@openai-curated"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."computer-use@openai-bundled"]
enabled = true

[plugins."slack@openai-curated"]
enabled = true

[plugins."linear@openai-curated"]
enabled = true

[plugins."sentry@openai-curated"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

[plugins."chrome@openai-bundled"]
enabled = true

[marketplaces.openai-bundled]
last_updated = "2026-05-17T04:11:36Z"
source_type = "local"
source = "/Users/akash/.codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.openai-primary-runtime]
last_updated = "2026-05-16T04:11:37Z"
source_type = "local"
source = "/Users/akash/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[tui.model_availability_nux]
"gpt-5.5" = 4

[mcp_servers.uidotsh]
url = "https://ui.sh/mcp?agent=codex"
http_headers = { Authorization = "Bearer CXEqI2XttgN1PleD66AbKjqSMBxGrbED" }

[mcp_servers.sentry]
enabled = true
url = "https://mcp.sentry.dev/mcp"
