[font]
size = 14
offset = { y = 1 }

[font.normal]
family = "Input Mono"
style = "Regular"

[[keyboard.bindings]]
action = "None"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "None"
key = "W"
mods = "Command"

[window]
decorations = "none"
startup_mode = "Maximized"
